services:
  verdaccio:
    image: node:18-alpine
    command: sh -c "cd /app && npm install --registry=https://registry.npmmirror.com && npm run start"
    container_name: verdaccio
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./:/app
    ports:
      - 4873:4873
    labels:
      createdBy: 'Apps'
networks:
  1panel-network:
    external: true
